"""Your descriptive messag2

Revision ID: 363f40751bd9
Revises: 90eda62c9c2b
Create Date: 2025-10-21 22:20:13.248612

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '363f40751bd9'
down_revision: Union[str, Sequence[str], None] = '90eda62c9c2b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order_detail',
    sa.Column('orderId', sa.String(length=10), nullable=False),
    sa.Column('itemCode', sa.String(length=10), nullable=False),
    sa.Column('qty', sa.Integer(), nullable=False),
    sa.Column('unitPrice', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['itemCode'], ['item_log.code'], ),
    sa.PrimaryKeyConstraint('orderId', 'itemCode')
    )
    op.create_index(op.f('ix_order_detail_orderId'), 'order_detail', ['orderId'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_order_detail_orderId'), table_name='order_detail')
    op.drop_table('order_detail')
    # ### end Alembic commands ###
