"""Your descriptive message

Revision ID: 51c010ebb5e5
Revises: ffab1db2ba4c
Create Date: 2025-10-15 10:14:30.816986

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '51c010ebb5e5'
down_revision: Union[str, Sequence[str], None] = 'ffab1db2ba4c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer_log', sa.Column('name', sa.String(length=100), nullable=False))
    op.add_column('customer_log', sa.Column('address', sa.String(length=100), nullable=False))
    op.add_column('customer_log', sa.Column('salary', sa.Float(), nullable=False))
    op.alter_column('customer_log', 'id',
               existing_type=mysql.INTEGER(),
               type_=sa.String(length=10),
               existing_nullable=False)
    op.drop_column('customer_log', 'user_question')
    op.drop_column('customer_log', 'timestamp')
    op.drop_column('customer_log', 'additional_info')
    op.drop_column('customer_log', 'bot_answer')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer_log', sa.Column('bot_answer', mysql.TEXT(), nullable=False))
    op.add_column('customer_log', sa.Column('additional_info', mysql.TEXT(), nullable=True))
    op.add_column('customer_log', sa.Column('timestamp', mysql.DATETIME(), server_default=sa.text('(now())'), nullable=False))
    op.add_column('customer_log', sa.Column('user_question', mysql.TEXT(), nullable=False))
    op.alter_column('customer_log', 'id',
               existing_type=sa.String(length=10),
               type_=mysql.INTEGER(),
               existing_nullable=False)
    op.drop_column('customer_log', 'salary')
    op.drop_column('customer_log', 'address')
    op.drop_column('customer_log', 'name')
    # ### end Alembic commands ###
