"""Your massege message

Revision ID: 7bfbad20a0c4
Revises: 607b4d625c47
Create Date: 2025-10-15 14:09:59.594090

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '7bfbad20a0c4'
down_revision: Union[str, Sequence[str], None] = '607b4d625c47'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_log', sa.Column('user_role', sa.Text(), nullable=False))
    op.add_column('chat_log', sa.Column('content', sa.Text(), nullable=False))
    op.drop_column('chat_log', 'user_question')
    op.drop_column('chat_log', 'additional_info')
    op.drop_column('chat_log', 'bot_answer')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_log', sa.Column('bot_answer', mysql.TEXT(), nullable=False))
    op.add_column('chat_log', sa.Column('additional_info', mysql.TEXT(), nullable=True))
    op.add_column('chat_log', sa.Column('user_question', mysql.TEXT(), nullable=False))
    op.drop_column('chat_log', 'content')
    op.drop_column('chat_log', 'user_role')
    # ### end Alembic commands ###
