"""Your descriptive message1

Revision ID: 90eda62c9c2b
Revises: 7bfbad20a0c4
Create Date: 2025-10-21 21:34:38.829186

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '90eda62c9c2b'
down_revision: Union[str, Sequence[str], None] = '7bfbad20a0c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('item_log',
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('description', sa.String(length=100), nullable=False),
    sa.Column('unitPrice', sa.Float(), nullable=False),
    sa.Column('qtyOnHand', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_index(op.f('ix_item_log_code'), 'item_log', ['code'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_item_log_code'), table_name='item_log')
    op.drop_table('item_log')
    # ### end Alembic commands ###
