"""Your descriptive 2

Revision ID: af4b2d7829f7
Revises: ba1cff8203f6
Create Date: 2025-10-23 11:53:51.548712

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'af4b2d7829f7'
down_revision: Union[str, Sequence[str], None] = 'ba1cff8203f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_log', sa.Column('session_id', sa.String(length=64), nullable=True))
    op.add_column('chat_log', sa.Column('sender', sa.String(length=50), nullable=False))
    op.add_column('chat_log', sa.Column('message_metadata', sa.Text(), nullable=True))
    op.add_column('chat_log', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.create_index(op.f('ix_chat_log_session_id'), 'chat_log', ['session_id'], unique=False)
    op.create_foreign_key(None, 'chat_log', 'sessions', ['session_id'], ['session_id'])
    op.drop_column('chat_log', 'timestamp')
    op.drop_column('chat_log', 'user_role')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_log', sa.Column('user_role', mysql.TEXT(), nullable=False))
    op.add_column('chat_log', sa.Column('timestamp', mysql.DATETIME(), server_default=sa.text('(now())'), nullable=False))
    op.drop_constraint(None, 'chat_log', type_='foreignkey')
    op.drop_index(op.f('ix_chat_log_session_id'), table_name='chat_log')
    op.drop_column('chat_log', 'created_at')
    op.drop_column('chat_log', 'message_metadata')
    op.drop_column('chat_log', 'sender')
    op.drop_column('chat_log', 'session_id')
    # ### end Alembic commands ###
