"""Your descriptive 1

Revision ID: b774d9c7ccff
Revises: af4b2d7829f7
Create Date: 2025-10-23 12:07:28.954772

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'b774d9c7ccff'
down_revision: Union[str, Sequence[str], None] = 'af4b2d7829f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat_log', 'message_metadata')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_log', sa.Column('message_metadata', mysql.TEXT(), nullable=True))
    # ### end Alembic commands ###
