"""Your descriptive mess2

Revision ID: ba1cff8203f6
Revises: 363f40751bd9
Create Date: 2025-10-22 10:20:49.655315

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'ba1cff8203f6'
down_revision: Union[str, Sequence[str], None] = '363f40751bd9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer_log', sa.Column('balance', sa.Float(), nullable=False))
    op.drop_column('customer_log', 'salary')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer_log', sa.Column('salary', mysql.FLOAT(), nullable=False))
    op.drop_column('customer_log', 'balance')
    # ### end Alembic commands ###
