"""customer table

Revision ID: ffab1db2ba4c
Revises: 6baea39d1c63
Create Date: 2025-10-14 15:36:41.601512

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ffab1db2ba4c'
down_revision: Union[str, Sequence[str], None] = '6baea39d1c63'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_question', sa.Text(), nullable=False),
    sa.Column('bot_answer', sa.Text(), nullable=False),
    sa.Column('additional_info', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customer_log_id'), 'customer_log', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_customer_log_id'), table_name='customer_log')
    op.drop_table('customer_log')
    # ### end Alembic commands ###
